### PR TITLE
Update Exiled.Events.EventArgs.StartingEventArgs

### PR DESCRIPTION
**Pull request by TrickyBestia**
Added IsAutoNuke property.

### CODE REVIEW

**Comment by galaxy119** [comment]
Rejected - You can get the info needed for these without using reflection.

**Comment by TrickyBestia** [comment]
@galaxy119, If you mean
`if (ev.Player == null || ev.Player == Server.Host)`
If you press Server events - Start round, ev.Player will be null (or Server.Host, i didn't check). Reflection works in 100%

**Comment by galaxy119** [comment]
I mean you can access the AlphawarheadController singleton via AlphawarheadController._host, rather than using reflection, which is slow.

**Comment by TrickyBestia** [comment]
@galaxy119, are you talking about I am using Warhead.Controller in my code?

**Comment by galaxy119** [comment]
No, I'm talking about accessing the warhead controller via AlphaWarheadController.Host instead of using reflection, which is slow. You also made this PR against master, instead of against our development branch. Either way, I implemented this myself via f6096bb

**Pull request closed without merging**
