### PR TITLE
[Documentation]: Debugging Symbols

### PR DESCRIPTION
**Pull request by ghost**
I've added more debug symbol configurations including `Embedded Debug Symbols` & `No Debug Symbols`.

`Embedded Debug Symbols` are added for `Debug` builds.
`Debug Symbols` are removed for `Optimized` builds.

#2338

### CODE REVIEW

**Comment by ALEXWARELLC** [comment]
@NaoUnderscore

**Comment by NaoUnderscore** [comment]
Tested?

**Comment by ALEXWARELLC** [comment]
> Tested?

Yep, I've gone ahead and tested everything, but feel free to perform your own tests.

**Comment by NaoUnderscore** [comment]
No I won't test it, I'm going to blame you if this breaks anything 🔥

**Pull request merged**
