### PR TITLE
Add location to plugins

### PR DESCRIPTION
**Pull request by PintTheDragon**
This will let you get the location of plugin dlls, because Plugin.Assembly.Location doesn't work.

### CODE REVIEW

**Comment by iopietro** [comment]
Why adding a `method` and a `Dictionary` instead of just a property in the `Plugin` class and `IPlugin` interface?

**Comment by iRebbok** [comment]
I'd suggest `Dictionary<Assembly, string>` to keep track of all locations including dependencies. I think it's better than a simple property in the `Plugin` class. @iopietro doesn't it?

**Comment by iopietro** [comment]
Sure, if we want to keep track of every assembly location, we can do that.

**Comment by PintTheDragon** [comment]
Yeah. I'm going to redo these changes with assembly keys.

**Comment by PintTheDragon** [comment]
There's a dictionary. People can use it. No helper stuff to get it but you can pretty easily get the assembly's location.

**Pull request merged**
