### PR TITLE
New extensions

### PR DESCRIPTION
**Pull request by SebasCapo**
- Added new Extensions for ItemTypes.
- Added new health-related extensions for ReferenceHubs.
- Added a maybe unnecessary bool for ReferenceHubs, but might make things simpler overall.

### CODE REVIEW

**Comment by FruitBoi** [comment]
Before I merge this, can i ask why you’re taking the maxHp of the player and subtracting the health of the player?

**Comment by SebasCapo** [comment]
Because setting the health value would allow you to go over the Max HP amount, which might be nice for some plugins, but you can still do that with the SetHealth method, in case Adrenaline HP isn't good enough for you :P 

Just thought that there should be a method that let's you add HP without surpassing the MaxHP limit.

**Comment by FruitBoi** [comment]
If we’re trying to not go over the max, wouldn’t Mathf.Clamp be a better option?

**Comment by SebasCapo** [comment]
Oh, didn't know those two existed, I'mma check those two out and edit the file

**Comment by SebasCapo** [comment]
Done, should be better now!

**Pull request merged**
