### PR TITLE
[Exiled::API] Added AccountAge to Features.Player

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by creepycats** [comment]
Just a thought but shouldn't this be only queried once? Every subsequent request is just an extra network call to fetch the AccountAge when you should only need to call it once and store the result. (Unless i'm stupid and stuff)

**Comment by louis1706** [comment]
> Just a thought but shouldn't this be only queried once? Every subsequent request is just an extra network call to fetch the AccountAge when you should only need to call it once and store the result. (Unless i'm stupid and stuff)

i actually don't feel like we should make an request to a website inside a property but i will let Nao see for it

**Comment by VALERA771** [comment]
I think w can use directly steam information and don't request any third-party websites

**Comment by creepycats** [comment]
The issue is Ive looked through Facepunch Steamworks.NET and there isnt a way to get the account age. If there is some secondary steam API dll we can use then try that but I dont think you can get it natively

**Comment by VALERA771** [comment]
We can access it through xml=1 (https://steamcpmmunity.com/profiles/{steamId}/?xml=1)

**Comment by creepycats** [comment]
Still, requesting a website isnt the greatest idea.

Then again not much else you can do.

**Comment by louis1706** [comment]
This has been refused because of the need of an actual HTTP request and it's conld lead to Lag if used during the gameplay

**Pull request closed without merging**
