### PR TITLE
Added automatic labeler system 

### PR DESCRIPTION
**Pull request by ghost**
This PR adds an automatic labeling system which detects modifications to certain files or folders & applies the respective label.

This can be adjusted but is here to provide a starting point to understand how the workflow works.

image

-  Pull Requests which modify `./Exiled.API` receives the `API` tag.
-  Pull Requests which modify `./Exiled.CustomModules` receives the `CustomModules` tag.
-  Pull Requests which modify `./Exiled.Events` receives the `Events` tag.
-  Pull Requests which modify `./Exiled.Installer` receives the `Installer` tag.
-  Pull Requests which modify `**/*.nuspec` receives the `NuGet` tag.
-  Pull Requests which modify `**/*.p1` or `**/*.p1` receives the `Scripts` tag.
-  Pull Requests which modify `./docs` receives the `docs` tag.

> NOTE: This WILL create new labels if they don't exist, so if you want to reassign each one to a preexisting one, you'll want to replace the label names.

### CODE REVIEW

**Comment by Vladislav-CS** [comment]
An interesting idea, can you test it on your repo?

**Comment by ALEXWARELLC** [comment]
> An interesting idea, can you test it on your repo? 

https://github.com/ALEXWARELLC/I-should-become-a-dev-for-doing-everything-nameless-doesnt/issues/5

**Comment by NaoUnderscore** [comment]
Great, I love it. Is there any chance we can use existing ones? In order to keep consistency with older PRs.

**Comment by ALEXWARELLC** [comment]
> Great, I love it. Is there any chance we can use existing ones? In order to keep consistency with older PRs.

Yeah, of course. This can be customised all the way down to a file specific level.

I'll try to use the pre-existing labels if possible.

**Comment by NaoUnderscore** [comment]
Is there any chance to rename the PR by prepending the `[Exiled.Module]` prefix?

**Comment by ALEXWARELLC** [comment]
> Is there any chance to rename the PR by prepending the `[Exiled.Module]` prefix?

If the files affected include the modules project, then I can write a step to rename the PR with the `[Exiled.Modules]` prefix.

**Comment by ALEXWARELLC** [comment]
> Is there any chance to rename the PR by prepending the `[Exiled.Module]` prefix?

Update: Unfortunately, I can't figure out how to name PRs.
There is little, to no documentation on how to rename pull requests.

**Comment by louis1706** [comment]
Very great idea

**Comment by ALEXWARELLC** [comment]
Hey!

I’m marking this pull request as draft as I feel I should write a complete GitHub actions workflow instead of creating individual pull requests for different actions which will be tied together anyway.

Thanks :)

**Pull request merged**
