### PR TITLE
Convert mute status changing events to IL patches.

### PR DESCRIPTION
**Pull request by steven4547466**
Converts `ChangingIntercomMuteStatus` and `ChangingMuteStatus` to IL patches. Their functionality remains the same.

### CODE REVIEW

**Review by iRebbok — CHANGES_REQUESTED** [review]
Use the new Harmony API like `WithLabels` and etc

**Review by steven4547466 — COMMENTED** [review]
Changed in latest commit

**Comment by iopietro** [comment]
Is this useful? Does it improve maintainability?
Transpilers are only useful when injecting code inside other portions of codes, to prevent copy-pasting things that you'll have to update everytime base-game devs change them.

**Comment by steven4547466** [comment]
Transpilers are more efficient than prefixes.

**Comment by Thundermaker300** [comment]
I feel as though prefixes are better for legibility and can be maintained much easier (there's more of us that can fix a prefix patch as opposed to a transpiler). However, in the case of what iopietro said, if northwood changes something often and we need to consistently keep up with it, transpilers are pretty neat

**Comment by iRebbok** [comment]
As the setters we patch don't contain any extra code that we might move/remove if it's useless, we don't need to use transpilers.
Transpilers are good when we want to patch a method in the middle (primary cause) or change the behavior of the method (second cause), they are also useful to patch at the end of the method, again, when we need to change the behavior.

In this case, transpilers make it difficult to maintain the code in the future.

**Pull request closed without merging**
