### PR TITLE
Add ChangedAttachmentsEvent

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by ALEXWARELLC** [comment]
Waiting for successful CI.

**Comment by Misfiy** [comment]
@ALEXWARELLC CI is successful

**Comment by Misfiy** [comment]
Tested by @ALEXWARELLC : Not working

**Comment by ALEXWARELLC** [comment]
Hello!

After performing some more tests, here's a bit more detail into what's happening.

## `Item.ChangingAmmo`
This works as expected. Below is image proof of `Item.ChangingAmmo` working.

image

## `Item.ChangedAttachments`
This DOES NOT work as expected. The event is effectively, never triggered, and needs to be fixed.

Thanks,
- Alex

**Comment by IkaOverride** [comment]
Fixed the patches
Fixed not being able to change the attachments in the ChangingAttachments event
Renamed "current" attachments to "old" attachments to be clearer

**Comment by ALEXWARELLC** [comment]
> Fixed the patches
> 
> Fixed editing the attachments not doing anything in ChangingAttachmentsEventArgs
> 
> Renamed "current" attachments to "old" attachments to be clearer

Should I test once more?

**Comment by IkaOverride** [comment]
I don't think, I tested a little bit and it was working

**Review by ALEXWARELLC — APPROVED** [review]
👍

**Review by Misfiy — APPROVED** [review]

**Pull request merged**
