### PR TITLE
Map.PlayGunSound

### PR DESCRIPTION
**Pull request by Banalny-Banan**
Added Map.PlayGunSound that allows to play a gun sound at specified position

### CODE REVIEW

**Comment by VALERA771** [comment]
This is just a copied method from MirrorExtensions with just replacing player with host

**Comment by Misfiy** [comment]
This should be into dev, not master

**Comment by Misaka-ZeroTwo** [comment]
Fix build errors

**Comment by Vladislav-CS** [comment]
This PR should target apis-rework, not master

**Comment by Vladislav-CS** [comment]
Just create another branch based on apis-rework and make the same changes and open a PR again

**Pull request closed without merging**
