### PR TITLE
`[Exiled::API]` `[Exiled::Events]` Danger fixes and additions

### PR DESCRIPTION
**Pull request by ghost**
- Added DangerTypeExtensions to Exiled.API.Extensions
- Added DangerType.None to the DangerType enum
- Added EncounteredPlayer to the ChangingDangerState event (can be null if it isn't an encounter danger)
- Fixed the ChangingDangerState event for all encounters and the damage dangers
- Player.Dangers now returns an empty array if the Scp1853 effect isn't enabled (to prevent issues and errors)
- Added Player.GetDanger(DangerType) and Player.TryGetDanger(DangerType, out DangerStackBase)

### CODE REVIEW

**Comment by IkaOverride** [comment]
it should be good (I hope because I'm not used to doing big pr) but hey I tested and it works on my machine! pls review code

**Review by obvEve — CHANGES_REQUESTED** [review]
Add ``DangerStackBase GetDanger(DangerType)`` in Player

**Comment by IkaOverride** [comment]
null is returned when the Scp1853 effect isn't active (because it caused issues)

**Comment by IkaOverride** [comment]
new commits are tested

**Review by obvEve — APPROVED** [review]

**Pull request merged**
